### ISSUE TITLE
The curve for Go and Node.js is not showing correctly

### ISSUE THREAD

**Issue by hsluoyz** [casbin/github-stars-history#3]
What I saw: 

![image](https://user-images.githubusercontent.com/3787410/85944666-329cd680-b96b-11ea-9f03-aa74e9039590.png)

What I expect:

https://star-history.t9t.io/#casbin/casbin&open-policy-agent/opa&ory/ladon

![image](https://user-images.githubusercontent.com/3787410/85948534-fc1f8580-b983-11ea-922e-baa16cd0df34.png)

**Comment by hsluoyz** [comment]
@xcaptain can you take it?

**Comment by hsluoyz** [comment]
Can anyone take this? @dovics @tldyl @kocoler @psiace @00LT00

**Comment by xcaptain** [comment]
#4 may help with the incorrect chart. it's because firebase cached incorrect data, press refresh all will pull all the data from github and update firebase
